import 'package:get/get_navigation/src/root/internacionalization.dart';

class LanguageModel extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_Us': {
          'create_own_profile': 'Create Your Own \nProfile',
          'enter_detail': 'Enter Your Details for Personalized \nExperience',
          'signup': 'Sign Up',
          'date_of_birth': 'Date of Birth',
          'choose_preferred_lang': 'Choose your preferred language',
          'your_detail': 'Your details',
          'full_name': 'Full name',
          'enter_full_name': 'Enter Full name',
          'birthday': 'MM / DD / YYYY',
          'gender': 'Gender',
          'select_gender': 'Select Your Gender',
          'nationality': 'Nationality',
          'select_nationality':'Select your Nationality',
          'weight': 'Weight',
          'enter_weight':'Enter Your Weight in KG',
          'continue': 'Continue',
          'agreement': 'AGREEMENT',
          'terms_condition': 'Terms & Conditions',
          'last_update': 'Last updated on 5/11/2024',
          'accept_terms_condition': 'Accept Terms & Conditions',
          'decline':'Decline',
          'create_health_profile': 'Create your personalized health profile',
          'get_started': 'Get started',
          'next': 'Next',
          'read_terms_condition': 'Read Terms & Conditions Before \nAccepting',
          'scroll_bottom': 'Scroll to Bottom',
          'personalise_experience': 'Personalise Your \nExperience',
          'fill_detail': 'Fill the details below to log in!',
          'english':'English',
          'arabic':'Arabic',
          'urdu':'Urdu',
          'who_are_you':'Who Are You?',
          'are_you_a':'Are You a Patient or a Doctor?',
          'patient':'Patient',
          'medical_professional':'Medical Professional',
          'medical_license':'Medical License',
          'institute':'Institute',
          'field':'Field',
          'upload_certificate':'Upload Certificates',
          'enter_institute':'Enter Name of Institute',
          'enter_field':'Enter Field of Expertise',
          'onboard_1_heading':'Your Partner in Safe \nMedication Choices',
          'onboard_1_text':'Pharmed empowers healthcare \ndecisions by helping patients and \npractitioners minimize errors and \ncreate tailored treatment strategies.',
          'skip':'Skip',
          'onboard_2_heading':'Simplifying Healthcare, \nOne Search at a Time',
         'onboard_2_text':'Explore a reliable medication search \nengine with usage information, side \neffects, and user feedback—ad-free \nand trustworthy.',
          'onboard_3_heading':'Join the Future of \nE-Health in UAE',
          'onboard_3_text':'Pharmed advances UAE’s e-health with \ninnovative tools, promoting public \nhealth and medication safety.',
          'already_have_account':'Already have an account?',
          'login':'Log In',
          'welcome':'Welcome 👋',
          'email':'Email',
          'enter_email':'Enter Email Address',
          'password':'Password',
          'enter_pass':'Enter Password',
          'dont_have_acc':'Don’t have an account?',
          'register':'Register Now',
          'forgot_pass':'Forgot Password?',
          'create_acc':'Create Your Account',
          'sign_up_text':'Sign Up & Enjoy the Best Healthcare \nExperience with Pharmed',
          'user_name':'User Name',
          'phone_number':'Phone Number',
          'enter_phone':'Enter Phone Number',
          'signin':'Sign in',
          'error':'Error',
          'please_select_role':'Please select a role',
          'welcome_to_dashboard':'Welcome To Your \nDashboard!',
          'popular':'Popular',
          'medical_history':'My Medical History',
          'search_medication':'Search Medication',
          'setting':'Settings',
          'search':'Search',
          'filter_by':'Filter By',
          'frequency':'Frequency',
          'dosage':'Dosage',
          'delete':'Delete',
          'edit':'Edit',
          'home':'Home',
          'connect_phar':'Connect',
          'dic':'DIC',
          'medicines':'Medicines',
          'notification':'Notification',
          'drug_interaction_checker':'Drug Interaction Checker',
          'add_drug_to_check':'Add Drug To Check For Interactions',
          'add_medicine_name':'Add Medicine Name...',
          'add_at_least':'Add At least 2 to 5 Drugs',
          'check_interaction':'Check Interaction',
          'clear':'Clear',
          'security_levels':'Security Levels :',
          'major':'Major',
          'moderate':'Moderate',
          'minor':'Minor',
          'major_level_desc':'Life-threatening or requiring immediate attention.',
          'moderate_level_desc':'Potentially significant, monitor closely or consult a professional.',
          'minor_level_desc':'Unlikely to cause harm but still worth noting',
          'interaction_found':'Interactions Found :',
          'read_terms':'Read Terms & Conditions',
          'read_privacy':'Read Privacy Policy',
          'change_language':'Change Language',
          'privacy_policy':'Privacy Policy',
          'signout':'Sign Out',
          'prescribing_physician_name':'Prescribing Physician Name',
          'enter_physician_name':'Enter Your Your Physician Name',
          'start_date':'Start Date',
          'enter_start_date':'Enter Start Date',
          'end_date':'End Date',
          'enter_end_date':'Enter End Date',
          'eg_500':'e.g 500mg',
          'eg_twice_daily':'e.g Twice Daily',
          'reason_for_use':'Reason For Use',
          'condition_or_symptom':'Condition or Symptom Being Treated...',
          'schedule_your_doses':'Schedule Your Doses',
          'set_your_date':'Set Your Date & Time',
          'set_refill_reminder':'Set Refill Reminders',
          'add_to_medicines':'Add to Medicines',
          'time':'Time',
          'medication':'Medication',
          'connect_pharm':'ConnectPhar',
          'select_language':'Select Language',
          'update':'Update',
          'read_terms_and_condition':'Read Terms & Conditions',
          'forgot_your_pass':'Forgot Your Password?',
          'forgot_pass_text':'Forgot Your Password? Enter Your Email to Get a OTP Code',
          'sent_otp':'Sent OTP',
          'enter_otp':'Enter OTP',
          'enter_otp_text':'Enter Your OTP to Reset Your Password',
          'dint_recieve_code':'Didn’t Receive the Code?',
          'resend':'Resend',
          'enter_new_password':'Enter New Password',
          'confirm_new_pass':'Confirm New Password',
          'update_password':'Update Password',
          'upload_medical_license':'Upload Medical License',
          'interaction_details':'Interaction Details',
          'drugs':'Drugs',
          'today':'Today',
          'type_message':'Type a message',
          'enter_login_otp':'Enter Your OTP which has been sent to you via email',
          '':'',
          '':'',
          '':'',
          '':'',
          '':'',
          '':'',
          '':'',
          '':'',
          '':'',

          

        },
        'ur_PK': {
          'create_own_profile':'اپنا پروفائل بنائیں',
          'enter_detail': 'اپنا تفصیلات درج کریں تاکہ ذاتی تجربہ حاصل ہو سکے',
          'signup': 'سائن اپ',
          'date_of_birth': 'تاریخ پیدائش',
          'choose_preferred_lang': 'اپنی پسندیدہ زبان منتخب کریں',
          'your_detail': 'آپ کی تفصیلات',
          'full_name': 'مکمل نام',
          'enter_full_name':'پورا نام درج کریں',
          'birthday': 'MM / DD / YYYY',
          'gender': 'جنس',
          'select_gender': 'اپنا جنس منتخب کریں',
          'nationality': 'قومیت',
          'select_nationality':'اپنی قومیت منتخب کریں',
          'weight': 'وزن',
          'enter_weight':'اپنے وزن کو کلوگرام میں درج کریں',
          'continue': 'جاری رکھیں',
          'agreement': 'معاہدہ',
          'terms_condition':'شرائط و ضوابط',
          'last_update': 'آخری بار اپ ڈیٹ کیا گیا 5/11/2024',
          'accept_terms_condition': 'شرائط و ضوابط کو قبول کریں',
          'decline':'رد کریں',
          'create_health_profile': 'اپنا ذاتی صحت پروفائل بنائیں',
          'get_started': 'شروع کریں',
          'next': 'اگلا',
          'read_terms_condition': 'پذیرش سے پہلے شرائط و ضوابط پڑھیں',
          'scroll_bottom': 'نیچے اسکرول کریں',
          'personalise_experience': 'اپنے تجربے کو ذاتی نوعیت دیں',
          'fill_detail': "لاگ ان کرنے کے لیے نیچے کی تفصیلات پُر کریں",
          'english':'انگریزی',
          'arabic':'عربی',
          'urdu':'اردو',
          'who_are_you':'تم کون ہو؟',
          'are_you_a':'کیا آپ مریض ہیں یا ڈاکٹر؟',
          'patient':'مریض',
          'medical_professional':'طبی ماہر',
          'medical_license':'طبی لائسنس',
          'institute':'انسٹی ٹیوٹ',
          'field':'میدان',
          'upload_certificate':'سرٹیفیکیٹس اپ لوڈ کریں',
          'enter_institute':'انسٹی ٹیوٹ کا نام درج کریں',
          'enter_field':'مہارت کا میدان درج کریں',
          'onboard_1_heading':'آپ کا ساتھی محفوظ دوا کے انتخاب میں',
          'onboard_1_text':'فارمیڈ صحت کے فیصلوں کو مضبوط بناتا ہے، مریضوں اور پریکٹیشنرز کی مدد کرتا ہے تاکہ وہ غلطیوں کو کم کریں اور حسب ضرورت علاج کی حکمت عملی تیار کریں۔',
          'skip':'چھوڑ دیں',
          'onboard_2_heading':'صحت کی دیکھ بھال کو آسان بنانا، ایک تلاش میں ایک وقت میں',
          'onboard_2_text':'ایک قابل اعتماد دوا تلاش کے انجن کو دریافت کریں جس میں استعمال کی معلومات، ضمنی اثرات، اور صارف کی آراء شامل ہوں— بغیر اشتہارات اور قابل اعتماد۔',
          'onboard_3_heading':'متحدہ عرب امارات میں ای ہیلتھ کے مستقبل کا حصہ بنیں',
          'onboard_3_text':'فارمیڈ یو اے ای کی ای ہیلتھ کو جدید ٹولز کے ساتھ ترقی دیتا ہے، جو عوامی صحت اور دوا کی حفاظت کو فروغ دیتا ہے۔',
          'already_have_account':'کیا آپ کا پہلے سے اکاؤنٹ ہے؟',
          'login':'لاگ ان کریں',
          'welcome':'👋خوش آمدید',
          'email':'ای میل',
          'enter_email':'ای میل پتہ درج کریں',
          'password':'پاس ورڈ',
          'enter_pass':'پاس ورڈ درج کریں',
          'dont_have_acc':'کیا آپ کا اکاؤنٹ نہیں ہے؟',
          'register':'ابھی رجسٹر کریں',
          'forgot_pass':'پاس ورڈ بھول گئے؟',
          'create_acc':'اپنا اکاؤنٹ بنائیں',
          'sign_up_text':'سائن اپ کریں اور فارمیڈ کے ساتھ بہترین صحت کی دیکھ بھال کا تجربہ حاصل کریں',
          'user_name':'صارف کا نام',
          'phone_number':'فون نمبر',
          'enter_phone':'فون نمبر درج کریں',
          'signin':'سائن ان کریں',
          'error':'غلطی',
          'please_select_role':'براہ کرم ایک کردار منتخب کریں',
          'welcome_to_dashboard':'آپ کے ڈیش بورڈ میں خوش آمدید',
          'popular':'مقبول',
          'medical_history':'میری طبی تاریخ',
          'search_medication':'ادویات تلاش کریں',
          'setting':'سیٹنگز',
          'search':'تلاش کریں',
          'filter_by':'کے ذریعہ فلٹر کریں',
          'frequency':'تعدد',
          'dosage':'خوراک',
          'delete':'حذف کریں',
          'edit':'ترمیم کریں',
          'home':'',
          'connect_phar':'کنیکٹ',
          'dic':'',
          'medicines':'دوائیاں',
          'notification':'اطلاع',
          'drug_interaction_checker':'دوا کی تعامل چیکر',
          'add_drug_to_check':'تعاملات چیک کرنے کے لیے دوا شامل کریں',
          'add_medicine_name':'دوا کا نام شامل کریں',
          'add_at_least':'کم از کم 2 سے 5 دوا شامل کریں',
          'check_interaction':'تعاملات چیک کریں',
          'clear':'صاف',
          'security_levels':':سیکیورٹی کی سطحیں',
          'major':'اہم',
          'moderate':'معتدل',
          'minor':'معمولی',
          'major_level_desc':'جان لیوا یا فوری توجہ کی ضرورت۔',
          'moderate_level_desc':'ممکنہ طور پر اہم، قریب سے نگرانی کریں یا کسی ماہر سے مشورہ کریں۔',
          'minor_level_desc':'نقصان کا امکان نہیں لیکن پھر بھی نوٹ کرنے کے قابل ہے۔',
          'interaction_found':'تعاملات دریافت ہوئیں',
          'read_terms':'شرائط و ضوابط پڑھیں',
          'read_privacy':'پرائیویسی پالیسی پڑھیں',
          'change_language':'زبان تبدیل کریں',
          'privacy_policy':'پرائیویسی پالیسی',
          'signout':'سائن آؤٹ کریں',
          'prescribing_physician_name':'تجویز کرنے والے معالج کا نام',
          'enter_physician_name':'اپنا معالج کا نام درج کریں',
          'start_date':'آغاز کی تاریخ',
          'enter_start_date':'آغاز کی تاریخ درج کریں',
          'end_date':'اختتامی تاریخ',
          'enter_end_date':'اختتامی تاریخ درج کریں',
          'eg_500':'mg500 مثلاً',
          'eg_twice_daily':'مثلاً دن میں دو بار',
          'reason_for_use':'استعمال کی وجہ',
          'condition_or_symptom':'...جس حالت یا علامت کا علاج کیا جا رہا ہے',
          'schedule_your_doses':'اپنی خوراک کا شیڈول مرتب کریں',
          'set_your_date':'اپنی تاریخ اور وقت سیٹ کریں',
          'set_refill_reminder':'ریفل کی یاد دہانیاں سیٹ کریں',
          'add_to_medicines':'ادویات میں اضافہ کریں',
          'time':'وقت',
          'medication':'دوا',
          'connect_pharm':'کنیکٹ فار',
          'select_language':'زبان منتخب کریں',
          'update':'اپ ڈیٹ',
          'read_terms_and_condition':'شرائط و ضوابط پڑھیں',
          'forgot_your_pass':'اپنا پاس ورڈ بھول گئے؟',
          'forgot_pass_text':'اپنا پاس ورڈ بھول گئے؟ اپنا ای میل درج کریں تاکہ آپ کو او ٹی پی کوڈ مل سکے۔',
          'sent_otp':'او ٹی پی بھیج دیا گیا',
          'enter_otp':'او ٹی پی درج کریں',
          'enter_otp_text':'اپنا او ٹی پی درج کریں تاکہ آپ اپنا پاس ورڈ ری سیٹ کر سکیں',
          'dint_recieve_code':'کوڈ موصول نہیں ہوا؟',
          'resend':'دوبارہ بھیجیں',
          'enter_new_password':'نیا پاس ورڈ درج کریں',
          'confirm_new_pass':'نیا پاس ورڈ تصدیق کریں',
          'update_password':'پاس ورڈ اپ ڈیٹ کریں',
          'upload_medical_license':'طبی لائسنس اپ لوڈ کریں',
          'interaction_details':'تعامل کی تفصیلات',
          'drugs':'ادویات',
          'today':'آج',
          'type_message':'ایک پیغام لکھیں',
          'enter_login_otp':'اپنا OTP درج کریں جو آپ کو ای میل کے ذریعے بھیجا گیا ہے۔'

        },
        'ar_AE': {
          'create_own_profile': 'أنشئ ملفك الشخصي',
          'enter_detail': 'أدخل تفاصيلك للحصول على تجربة مخصصة',
          'signup': 'التسجيل',
          'date_of_birth': 'تاريخ الميلاد',
          'choose_preferred_lang': 'اختر لغتك المفضلة',
          'your_detail': 'تفاصيلك',
          'full_name': 'الاسم الكامل',
          'enter_full_name':'أدخل الاسم الكامل',
          'birthday': 'MM / DD / YYYY',
          'gender': 'الجنس',
          'select_gender': 'اختر جنسك',
          'nationality': 'الجنسية',
          'select_nationality':'اختر جنسيتك',
          'weight': 'الوزن',
          'enter_weight':'أدخل وزنك بالكيلوغرام',
          'continue': 'متابعة',
          'agreement': 'اتفاقية',
          'terms_condition': 'الشروط والأحكام',
          'last_update': 'آخر تحديث في 5/11/2024',
          'accept_terms_condition': 'قبول الشروط والأحكام',
          'create_health_profile':'أنشئ ملفك الصحي الشخصي',
          'decline':'رفض',
          'get_started': 'ابدأ',
          'next': 'التالي',
          'read_terms_condition': 'اقرأ الشروط والأحكام قبل القبول',
          'scroll_bottom': 'مرر لأسفل',
          'personalise_experience': 'خصص تجربتك',
          'fill_detail': 'املأ التفاصيل أدناه لتسجيل الدخول',
          'english':'الإنجليزية',
          'arabic':'العربية',
          'urdu':'الأردية',
          'who_are_you':'من أنت؟',
          'are_you_a':'هل أنت مريض أم طبيب؟',
          'patient':'مريض',
          'medical_professional':'محترف طبي',
          'medical_license':'رخصة طبية',
          'institute':'معهد',
          'field':'مجال',
          'upload_certificate':'رفع الشهادات',
          'enter_institute':'أدخل اسم المعهد',
          'enter_field':'أدخل مجال التخصص',
          'onboard_1_heading':'شريكك في اختيارات الدواء الآمنة',
          'onboard_1_text':'فارمد يعزز قرارات الرعاية الصحية من خلال مساعدة المرضى والممارسين في تقليل الأخطاء وابتكار استراتيجيات علاج مخصصة',
          'skip':'تخطي',
          'onboard_2_heading':'تبسيط الرعاية الصحية، بحث واحد في كل مرة',
          'onboard_2_text':'استكشف محرك بحث موثوق للأدوية مع معلومات الاستخدام، والآثار الجانبية، وتعليقات المستخدمين—خالي من الإعلانات وموثوق.',
          'onboard_3_heading':'انضم إلى مستقبل الصحة الإلكترونية في الإمارات العربية المتحدة',
          'onboard_3_text':'فارمد يطور الصحة الإلكترونية في الإمارات باستخدام أدوات مبتكرة، ويعزز الصحة العامة وسلامة الأدوية.',
          'already_have_account':'هل لديك حساب بالفعل؟',
          'login':'تسجيل الدخول',
          'welcome':'👋مرحبًا',
          'email':'البريد الإلكتروني',
          'enter_email':'أدخل عنوان البريد الإلكتروني',
          'password':'كلمة المرور',
          'enter_pass':'أدخل كلمة المرور',
          'dont_have_acc':'ليس لديك حساب؟',
          'register':'سجل الآن',
          'forgot_pass':'نسيت كلمة المرور؟',
          'create_acc':'أنشئ حسابك',
          'sign_up_text':'سجل الآن واستمتع بأفضل تجربة رعاية صحية مع فارمد',
          'user_name':'اسم المستخدم',
          'phone_number':'رقم الهاتف',
          'enter_phone':'أدخل رقم الهاتف',
          'signin':'تسجيل الدخول',
          'error':'خطأ',
          'please_select_role':'يرجى اختيار دور',
          'welcome_to_dashboard':'أهلاً وسهلاً في لوحة القيادة الخاصة بك',
          'popular':'شائع',
          'medical_history':'تاريخي الطبي',
          'search_medication':'ابحث عن الأدوية',
          'setting':'الإعدادات',
          'search':'بحث',
          'filter_by':'تصفية حسب',
          'frequency':'التكرار',
          'dosage':'الجرعة',
          'delete':'حذف',
          'edit':'تعديل',
          'home':'',
          'connect_phar':'ربط',
          'dic':'',
          'medicines':'أدوية',
          'notification':'إشعار',
          'drug_interaction_checker':'فاحص تفاعل الأدوية',
          'add_drug_to_check':'أضف الدواء للتحقق من التفاعلات',
          'add_medicine_name':'أضف اسم الدواء',
          'add_at_least':'أضف على الأقل 2 إلى 5 أدوية',
          'check_interaction':'تحقق من التفاعل',
          'clear':'مسح',
          'security_levels':':مستويات الأمان',
          'major':'رئيسي',
          'moderate':'معتدل',
          'minor':'طفيف',
          'major_level_desc':' مهدد للحياة أو يتطلب اهتمامًا فوريًا',
          'moderate_level_desc':'محتمل أن يكون ذا أهمية، راقب عن كثب أو استشر مختصًا',
          'minor_level_desc':'من غير المحتمل أن يسبب ضررًا ولكن يستحق الملاحظة',
          'interaction_found':'تم العثور على التفاعلات',
          'read_terms':'اقرأ الشروط والأحكام',
          'read_privacy':'اقرأ سياسة الخصوصية',
          'change_language':'تغيير اللغة',
          'privacy_policy':'سياسة الخصوصية',
          'signout':'تسجيل الخروج',
          'prescribing_physician_name':'اسم الطبيب المعالج',
          'enter_physician_name':'أدخل اسم طبيبك',
          'start_date':'تاريخ البدء',
          'enter_start_date':'أدخل تاريخ البدء',
          'end_date':'تاريخ الانتهاء',
          'enter_end_date':'أدخل تاريخ الانتهاء',
          'eg_500':'mg500 على سبيل المثال',
          'eg_twice_daily':'على سبيل المثال مرتين في اليوم',
          'reason_for_use':'سبب الاستخدام',
          'condition_or_symptom':' ...الحالة أو العرض الذي يتم معالجته',
          'schedule_your_doses':'جدولة جرعاتك',
          'set_your_date':'حدد تاريخك ووقتك',
          'set_refill_reminder':'حدد تذكيرات التعبئة',
          'add_to_medicines':'أضف إلى الأدوية',
          'time':'وقت',
          'medication':'دواء',
          'connect_pharm':'ربط فار',
          'select_language':'اختر اللغة',
          'update':'تحديث',
          'read_terms_and_condition':'اقرأ الشروط والأحكام',
          'forgot_your_pass':'هل نسيت كلمة المرور؟',
          'forgot_pass_text':'نسيت كلمة السر؟ أدخل بريدك الإلكتروني للحصول على رمز OTP',
          'sent_otp':'تم إرسال رمز OTP',
          'enter_otp':'Arabic: أدخل رمز OTP',
          'enter_otp_text':' أدخل رمز OTP لإعادة تعيين كلمة المرور الخاصة بك',
          'dint_recieve_code':'لم تستلم الرمز؟',
          'resend':'أعد الإرسال',
          'enter_new_password':'أدخل كلمة المرور الجديدة',
          'confirm_new_pass':'أكد كلمة المرور الجديدة',
          'update_password':'تحديث كلمة المرور',
          'upload_medical_license':'رفع الرخصة الطبية',
          'interaction_details':'تفاصيل التفاعل',
          'drugs':'الأدوية',
          'today':'اليوم',
          'type_message':'اكتب رسالة',
          'enter_login_otp':'أدخل رمز OTP الخاص بك الذي تم إرساله إليك عبر البريد الإلكتروني',
          '':'',
          '':'',
          '':'',
          '':'',


        },
      };
}
