name: pharmed_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+4

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  custom_otp_textfield: ^0.0.2
  custom_refresh_indicator: ^4.0.1
  encrypt: ^5.0.3
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  
  
  # flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_local_notifications: ^17.0.0
  flutter_otp_text_field: ^1.4.0+2
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  
  flutter_timezone: ^4.1.0
  flutter_widget_from_html: ^0.15.3
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  horizontal_week_calendar: ^0.0.18
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pinput: ^5.0.1
  share_plus: ^10.1.3
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  textfield_search: ^0.11.1
  textfield_tags: ^3.0.1
  timezone: ^0.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
      
